### PR TITLE
chore: scripts optimization

### PR DESCRIPTION
**Pull request by whxaxes**
##### Checklist

- [x] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change

Migrating `egg-ts-helper/register` to `egg.require` due to https://github.com/eggjs/egg-bin/pull/121

### CODE REVIEW

**Comment by atian25** [comment]
你合并发吧

**Comment by whxaxes** [comment]
我没有权限，还是你发一下吧 @atian25

**Comment by whxaxes** [comment]
我推了 tag ，但是推不了更改到 master

**Comment by whxaxes** [comment]
1.4.0

**Pull request merged**
